project:
  type: website
  output-dir: docs

website:
  title: "Joshua P. French"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - software.qmd
      - teaching.qmd

format:
  html:
    theme:
      - simplex
      - custom.scss
    css: styles.css
    toc: true
